name: Cross-compile Fyne App with fyne-cross

on:
  push:
    branches:
      - main  # 可以根据需要修改触发条件

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'  # 设置 Go 版本，确保和你的项目兼容

    - name: Install dependencies
      run: |
        # 安装 fyne-cross 和其他必要的依赖
        sudo apt-get update
        sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libxtst-dev libxrandr-dev libxi-dev libgl-dev libudev-dev

        # 安装 fyne-cross 工具
        go install github.com/fyne-io/fyne-cross/v2/cmd/fyne-cross@latest

    - name: Cross-compile Fyne application
      run: |
        # 创建输出目录
        mkdir -p dist

        # 使用 fyne-cross 进行交叉编译，生成目标平台的二进制文件
        fyne-cross -os linux -arch amd64 -output dist/
        fyne-cross -os windows -arch amd64 -output dist/
        fyne-cross -os darwin -arch amd64 -output dist/

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fyne-cross-builds
        path: dist/

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
