name: Build and Cross-Compile Fyne App with fyne-cross

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # 使用 Ubuntu 作为构建环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23' # 或者你需要的 Go 版本

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Pull fyne-cross Docker image
        run: docker pull fyneio/fyne-cross

      - name: Cross-compile with fyne-cross
        run: |
          docker run --rm -v $(pwd):/app fyneio/fyne-cross -icon=myicon.png -app-id=com.example.myapp linux -arch=amd64
          docker run --rm -v $(pwd):/app fyneio/fyne-cross -icon=myicon.png -app-id=com.example.myapp linux -arch=arm64
          docker run --rm -v $(pwd):/app fyneio/fyne-cross -icon=myicon.png -app-id=com.example.myapp darwin -arch=amd64
          docker run --rm -v $(pwd):/app fyneio/fyne-cross -icon=myicon.png -app-id=com.example.myapp darwin -arch=arm64
          docker run --rm -v $(pwd):/app fyneio/fyne-cross -icon=myicon.ico -app-id=com.example.myapp windows -arch=amd64

      - name: Rename output files
        run: |
          mv myapp-linux-amd64 myapp-linux-amd64-${{ github.sha }}
          mv myapp-linux-arm64 myapp-linux-arm64-${{ github.sha }}
          mv myapp-darwin-amd64 myapp-darwin-amd64-${{ github.sha }}
          mv myapp-darwin-arm64 myapp-darwin-arm64-${{ github.sha }}
          mv myapp-windows-amd64.exe myapp-windows-amd64-${{ github.sha }}.exe

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            myapp-linux-amd64-${{ github.sha }}
            myapp-linux-arm64-${{ github.sha }}
            myapp-darwin-amd64-${{ github.sha }}
            myapp-darwin-arm64-${{ github.sha }}
            myapp-windows-amd64-${{ github.sha }}.exe
