name: Build Fyne App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'  # 设置Go版本，确保和你的项目兼容

    - name: Install Fyne CLI
      run: |
        curl -s https://fyne.io/downloads/ | bash
        export PATH=$PATH:$HOME/go/bin

    - name: Get version from tag
      id: version
      run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV

    - name: Build the Fyne app
      run: |
        mkdir -p dist
        fyne package -os linux -icon ./assets/icon.png -name "Mi Router BE5000 (RD18) Get SSH Tool ${VERSION}" -output dist/
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: dist/

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
